### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by matthiasa4** [googleapis/python-recommendations-ai#16]
When trying to use the example code provided in the [documentation](https://googleapis.dev/java/google-cloud-recommendations-ai/latest/index.html) to speak to the Recommendation AI API through the Java client to create CatalogItems, I run into the above Exception. 

Full stack trace:
```
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object)'
        at io.grpc.Metadata$Key.validateName(Metadata.java:742)
        at io.grpc.Metadata$Key.<init>(Metadata.java:750)
        at io.grpc.Metadata$Key.<init>(Metadata.java:668)
        at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:959)
        at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:954)
        at io.grpc.Metadata$Key.of(Metadata.java:705)
        at io.grpc.Metadata$Key.of(Metadata.java:701)
        at com.google.api.gax.grpc.GrpcHeaderInterceptor.<init>(GrpcHeaderInterceptor.java:60)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:239)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:210)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:217)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:200)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
        at com.google.cloud.recommendationengine.v1beta1.stub.GrpcCatalogServiceStub.create(GrpcCatalogServiceStub.java:142)
        at com.google.cloud.recommendationengine.v1beta1.stub.CatalogServiceStubSettings.createStub(CatalogServiceStubSettings.java:163)
        at com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient.<init>(CatalogServiceClient.java:146)
        at com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient.create(CatalogServiceClient.java:127)
        at com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient.create(CatalogServiceClient.java:118)
        at com.mbae.RecommendationEngineApiSample.main(RecommendationEngineApiSample.java:50)
```

Relevant code:
```
import com.google.cloud.recommendationengine.v1beta1.CatalogServiceClient;

public class RecommendationEngineApiSample {
    public static void main(String[] args) throws IOException {
        try (CatalogServiceClient catalogServiceClient = CatalogServiceClient.create()) {
            CatalogName parent = CatalogName.of("[PROJECT]", "[LOCATION]", "[CATALOG]");
            CatalogItem catalogItem = CatalogItem.newBuilder().build();
            CatalogItem response = catalogServiceClient.createCatalogItem(parent, catalogItem);
        }
    }
}
```

Am I missing something? Any help would be appreciated.

**Comment by busunkim96** [comment]
Hi @matthiasa4,

Please open this issue in the Java client library repository. https://github.com/googleapis/java-recommendations-ai/issues

**Comment by matthiasa4** [comment]
Of course - my apologies @busunkim96 I wrote this in the wrong tab :)
